import aiosqlite

# (name, muscle_group, sub_muscle_group, exercise_type, equipment, default_rating)
EXERCISES = [
    # === Legs (45: 12 compound, 33 isolation) ===
    ("Barbell Back Squat", "Legs", "Quadriceps", "compound", "Barbell", 5),
    ("Conventional Deadlift", "Legs", "Posterior Chain", "compound", "Barbell", 5),
    ("Romanian Deadlift", "Legs", "Hamstrings", "compound", "Barbell", 4),
    ("Leg Press", "Legs", "Quadriceps", "compound", "Machine", 4),
    ("Hack Squat", "Legs", "Quadriceps", "compound", "Machine", 4),
    ("Front Squat", "Legs", "Quadriceps", "compound", "Barbell", 4),
    ("Bulgarian Split Squat", "Legs", "Quadriceps", "compound", "Dumbbell", 3),
    ("Goblet Squat", "Legs", "Quadriceps", "compound", "Dumbbell", 3),
    ("Sumo Deadlift", "Legs", "Posterior Chain", "compound", "Barbell", 4),
    ("Walking Lunge", "Legs", "Quadriceps", "compound", "Dumbbell", 3),
    ("Barbell Lunge", "Legs", "Quadriceps", "compound", "Barbell", 3),
    ("Trap Bar Deadlift", "Legs", "Posterior Chain", "compound", "Trap Bar", 4),
    ("Seated Hamstring Curl", "Legs", "Hamstrings", "isolation", "Machine", 3),
    ("Lying Hamstring Curl", "Legs", "Hamstrings", "isolation", "Machine", 3),
    ("Seated Quad Extension", "Legs", "Quadriceps", "isolation", "Machine", 3),
    ("Hip Adduction", "Legs", "Adductors", "isolation", "Machine", 3),
    ("Hip Abduction", "Legs", "Abductors", "isolation", "Machine", 3),
    ("Standing Calf Raise", "Legs", "Calves", "isolation", "Machine", 3),
    ("Seated Calf Raise", "Legs", "Calves", "isolation", "Machine", 3),
    ("Single-Leg Hamstring Curl", "Legs", "Hamstrings", "isolation", "Machine", 3),
    ("Nordic Hamstring Curl", "Legs", "Hamstrings", "isolation", "Bodyweight", 3),
    ("Sissy Squat", "Legs", "Quadriceps", "isolation", "Bodyweight", 3),
    ("Leg Press Calf Raise", "Legs", "Calves", "isolation", "Machine", 3),
    ("Cable Kickback", "Legs", "Glutes", "isolation", "Cable", 3),
    ("Glute Bridge", "Legs", "Glutes", "isolation", "Barbell", 3),
    ("Hip Thrust", "Legs", "Glutes", "isolation", "Barbell", 4),
    ("Single-Leg Hip Thrust", "Legs", "Glutes", "isolation", "Bodyweight", 3),
    ("Cable Pull-Through", "Legs", "Glutes", "isolation", "Cable", 3),
    ("Reverse Lunge (Dumbbell)", "Legs", "Quadriceps", "isolation", "Dumbbell", 3),
    ("Step-Up", "Legs", "Quadriceps", "isolation", "Dumbbell", 3),
    ("Donkey Calf Raise", "Legs", "Calves", "isolation", "Machine", 3),
    ("Good Morning", "Legs", "Hamstrings", "isolation", "Barbell", 3),
    ("Cable Adduction", "Legs", "Adductors", "isolation", "Cable", 3),
    ("Cable Abduction", "Legs", "Abductors", "isolation", "Cable", 3),
    ("Single-Leg Leg Press", "Legs", "Quadriceps", "isolation", "Machine", 3),
    ("Single-Leg Extension", "Legs", "Quadriceps", "isolation", "Machine", 3),
    ("Kettlebell Swing", "Legs", "Posterior Chain", "isolation", "Kettlebell", 3),
    ("Reverse Hyperextension", "Legs", "Glutes", "isolation", "Machine", 3),
    ("Glute Ham Raise", "Legs", "Hamstrings", "isolation", "Machine", 3),
    ("Smith Machine Squat", "Legs", "Quadriceps", "isolation", "Smith Machine", 3),
    ("Pendulum Squat", "Legs", "Quadriceps", "isolation", "Machine", 3),
    ("Belt Squat", "Legs", "Quadriceps", "isolation", "Machine", 3),
    ("Banded Lateral Walk", "Legs", "Abductors", "isolation", "Resistance Band", 3),
    ("Frog Pump", "Legs", "Glutes", "isolation", "Bodyweight", 3),
    ("Tibialis Raise", "Legs", "Tibialis", "isolation", "Machine", 3),

    # === Chest (40: 12 compound, 28 isolation) ===
    ("Barbell Bench Press", "Chest", "Pectorals", "compound", "Barbell", 5),
    ("Incline Barbell Bench", "Chest", "Upper Pecs", "compound", "Barbell", 4),
    ("Dumbbell Bench Press", "Chest", "Pectorals", "compound", "Dumbbell", 4),
    ("Incline Dumbbell Press", "Chest", "Upper Pecs", "compound", "Dumbbell", 4),
    ("Push-Up", "Chest", "Pectorals", "compound", "Bodyweight", 3),
    ("Decline Barbell Bench", "Chest", "Lower Pecs", "compound", "Barbell", 3),
    ("Decline Dumbbell Press", "Chest", "Lower Pecs", "compound", "Dumbbell", 3),
    ("Close-Grip Bench Press (Chest)", "Chest", "Inner Pecs", "compound", "Barbell", 3),
    ("Smith Machine Bench Press", "Chest", "Pectorals", "compound", "Smith Machine", 3),
    ("Smith Machine Incline Press", "Chest", "Upper Pecs", "compound", "Smith Machine", 3),
    ("Machine Chest Press", "Chest", "Pectorals", "compound", "Machine", 3),
    ("Weighted Dip (Chest)", "Chest", "Lower Pecs", "compound", "Bodyweight", 4),
    ("Cable Fly", "Chest", "Pectorals", "isolation", "Cable", 3),
    ("Pec Deck", "Chest", "Pectorals", "isolation", "Machine", 3),
    ("Dumbbell Fly", "Chest", "Pectorals", "isolation", "Dumbbell", 3),
    ("Low Cable Fly", "Chest", "Upper Pecs", "isolation", "Cable", 3),
    ("High Cable Fly", "Chest", "Lower Pecs", "isolation", "Cable", 3),
    ("Incline Dumbbell Fly", "Chest", "Upper Pecs", "isolation", "Dumbbell", 3),
    ("Decline Dumbbell Fly", "Chest", "Lower Pecs", "isolation", "Dumbbell", 3),
    ("Cable Crossover", "Chest", "Pectorals", "isolation", "Cable", 3),
    ("Svend Press", "Chest", "Inner Pecs", "isolation", "Dumbbell", 3),
    ("Machine Fly", "Chest", "Pectorals", "isolation", "Machine", 3),
    ("Single-Arm Cable Fly", "Chest", "Pectorals", "isolation", "Cable", 3),
    ("Incline Cable Fly", "Chest", "Upper Pecs", "isolation", "Cable", 3),
    ("Decline Cable Fly", "Chest", "Lower Pecs", "isolation", "Cable", 3),
    ("Dumbbell Pullover", "Chest", "Pectorals", "isolation", "Dumbbell", 3),
    ("Push-Up (Wide Grip)", "Chest", "Outer Pecs", "isolation", "Bodyweight", 3),
    ("Push-Up (Diamond)", "Chest", "Inner Pecs", "isolation", "Bodyweight", 3),
    ("Plate Squeeze Press", "Chest", "Inner Pecs", "isolation", "Plate", 3),
    ("Incline Push-Up", "Chest", "Lower Pecs", "isolation", "Bodyweight", 3),
    ("Decline Push-Up", "Chest", "Upper Pecs", "isolation", "Bodyweight", 3),
    ("Cable Iron Cross", "Chest", "Pectorals", "isolation", "Cable", 3),
    ("Hex Press", "Chest", "Inner Pecs", "isolation", "Dumbbell", 3),
    ("Single-Arm Dumbbell Fly", "Chest", "Pectorals", "isolation", "Dumbbell", 3),
    ("Resistance Band Fly", "Chest", "Pectorals", "isolation", "Resistance Band", 3),
    ("Floor Fly", "Chest", "Pectorals", "isolation", "Dumbbell", 3),
    ("Machine Incline Press", "Chest", "Upper Pecs", "isolation", "Machine", 3),
    ("Chest Dip (Bodyweight)", "Chest", "Lower Pecs", "isolation", "Bodyweight", 3),
    ("Standing Cable Press", "Chest", "Pectorals", "isolation", "Cable", 3),
    ("Landmine Press (Chest)", "Chest", "Upper Pecs", "isolation", "Barbell", 3),

    # === Back (42: 12 compound, 30 isolation) ===
    ("Barbell Row", "Back", "Lats/Rhomboids", "compound", "Barbell", 5),
    ("Pull-Up", "Back", "Lats", "compound", "Bodyweight", 5),
    ("Lat Pulldown", "Back", "Lats", "compound", "Cable", 4),
    ("Seated Cable Row", "Back", "Mid-Back", "compound", "Cable", 4),
    ("Dumbbell Row", "Back", "Lats", "compound", "Dumbbell", 4),
    ("T-Bar Row", "Back", "Mid-Back", "compound", "Barbell", 4),
    ("Chin-Up", "Back", "Lats", "compound", "Bodyweight", 4),
    ("Pendlay Row", "Back", "Mid-Back", "compound", "Barbell", 3),
    ("Meadows Row", "Back", "Lats", "compound", "Barbell", 3),
    ("Machine Row", "Back", "Mid-Back", "compound", "Machine", 3),
    ("Chest-Supported Row", "Back", "Mid-Back", "compound", "Dumbbell", 3),
    ("Inverted Row", "Back", "Mid-Back", "compound", "Bodyweight", 3),
    ("Face Pull", "Back", "Rear Delts", "isolation", "Cable", 3),
    ("Straight-Arm Pulldown", "Back", "Lats", "isolation", "Cable", 3),
    ("Reverse Cable Fly", "Back", "Mid-Back", "isolation", "Cable", 3),
    ("Single-Arm Lat Pulldown", "Back", "Lats", "isolation", "Cable", 3),
    ("Single-Arm Cable Row", "Back", "Lats", "isolation", "Cable", 3),
    ("Wide-Grip Lat Pulldown", "Back", "Lats", "isolation", "Cable", 3),
    ("Close-Grip Lat Pulldown", "Back", "Lats", "isolation", "Cable", 3),
    ("Reverse-Grip Lat Pulldown", "Back", "Lats", "isolation", "Cable", 3),
    ("Dumbbell Pullover (Back)", "Back", "Lats", "isolation", "Dumbbell", 3),
    ("Cable Pullover", "Back", "Lats", "isolation", "Cable", 3),
    ("Machine Pullover", "Back", "Lats", "isolation", "Machine", 3),
    ("Hyperextension", "Back", "Lower Back", "isolation", "Bodyweight", 3),
    ("Reverse Hyperextension (Back)", "Back", "Lower Back", "isolation", "Machine", 3),
    ("Rack Pull", "Back", "Lower Back", "isolation", "Barbell", 3),
    ("Band Pull-Apart", "Back", "Rear Delts", "isolation", "Resistance Band", 3),
    ("Prone Y Raise", "Back", "Lower Traps", "isolation", "Dumbbell", 3),
    ("Prone I Raise", "Back", "Lower Traps", "isolation", "Dumbbell", 3),
    ("Shrug", "Back", "Upper Traps", "isolation", "Barbell", 3),
    ("Dumbbell Shrug", "Back", "Upper Traps", "isolation", "Dumbbell", 3),
    ("Cable Shrug", "Back", "Upper Traps", "isolation", "Cable", 3),
    ("Behind-the-Back Shrug", "Back", "Upper Traps", "isolation", "Barbell", 3),
    ("Seal Row", "Back", "Mid-Back", "isolation", "Barbell", 3),
    ("Machine Lat Pulldown", "Back", "Lats", "isolation", "Machine", 3),
    ("Reverse Pec Deck", "Back", "Rear Delts", "isolation", "Machine", 3),
    ("Seated Face Pull", "Back", "Rear Delts", "isolation", "Cable", 3),
    ("Cable Y Raise", "Back", "Lower Traps", "isolation", "Cable", 3),
    ("Kelso Shrug", "Back", "Mid-Back", "isolation", "Dumbbell", 3),
    ("Kroc Row", "Back", "Lats", "isolation", "Dumbbell", 3),
    ("Landmine Row", "Back", "Lats", "isolation", "Barbell", 3),
    ("Superman Hold", "Back", "Lower Back", "isolation", "Bodyweight", 3),

    # === Shoulders (41: 8 compound, 33 isolation) ===
    ("Overhead Press", "Shoulders", "Anterior Delt", "compound", "Barbell", 5),
    ("Dumbbell Shoulder Press", "Shoulders", "Anterior Delt", "compound", "Dumbbell", 4),
    ("Arnold Press", "Shoulders", "All Delts", "compound", "Dumbbell", 4),
    ("Push Press", "Shoulders", "Anterior Delt", "compound", "Barbell", 3),
    ("Landmine Press", "Shoulders", "Anterior Delt", "compound", "Barbell", 3),
    ("Smith Machine Overhead Press", "Shoulders", "Anterior Delt", "compound", "Smith Machine", 3),
    ("Machine Shoulder Press", "Shoulders", "Anterior Delt", "compound", "Machine", 3),
    ("Viking Press", "Shoulders", "Anterior Delt", "compound", "Machine", 3),
    ("Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Front Raise", "Shoulders", "Anterior Delt", "isolation", "Dumbbell", 3),
    ("Rear Delt Fly", "Shoulders", "Posterior Delt", "isolation", "Dumbbell", 3),
    ("Cable Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Cable", 3),
    ("Cable Front Raise", "Shoulders", "Anterior Delt", "isolation", "Cable", 3),
    ("Cable Rear Delt Fly", "Shoulders", "Posterior Delt", "isolation", "Cable", 3),
    ("Machine Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Machine", 3),
    ("Machine Rear Delt Fly", "Shoulders", "Posterior Delt", "isolation", "Machine", 3),
    ("Dumbbell Y Raise", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Plate Front Raise", "Shoulders", "Anterior Delt", "isolation", "Plate", 3),
    ("Leaning Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Behind-the-Back Cable Lateral", "Shoulders", "Lateral Delt", "isolation", "Cable", 3),
    ("Seated Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Incline Rear Delt Fly", "Shoulders", "Posterior Delt", "isolation", "Dumbbell", 3),
    ("Prone Rear Delt Raise", "Shoulders", "Posterior Delt", "isolation", "Dumbbell", 3),
    ("Cable Face Pull (Shoulders)", "Shoulders", "Posterior Delt", "isolation", "Cable", 3),
    ("Lu Raise", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Dumbbell Upright Row", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Cable Upright Row", "Shoulders", "Lateral Delt", "isolation", "Cable", 3),
    ("Barbell Upright Row", "Shoulders", "Lateral Delt", "isolation", "Barbell", 3),
    ("Resistance Band Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Resistance Band", 3),
    ("Resistance Band Pull-Apart (Shoulders)", "Shoulders", "Posterior Delt", "isolation", "Resistance Band", 3),
    ("Single-Arm Cable Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Cable", 3),
    ("Bus Driver", "Shoulders", "Anterior Delt", "isolation", "Plate", 3),
    ("W Raise", "Shoulders", "Posterior Delt", "isolation", "Dumbbell", 3),
    ("Scaption", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Cuban Press", "Shoulders", "Posterior Delt", "isolation", "Dumbbell", 3),
    ("Bradford Press", "Shoulders", "All Delts", "isolation", "Barbell", 3),
    ("Egyptian Lateral Raise", "Shoulders", "Lateral Delt", "isolation", "Cable", 3),
    ("Reverse Cable Crossover", "Shoulders", "Posterior Delt", "isolation", "Cable", 3),
    ("Scott Press", "Shoulders", "Lateral Delt", "isolation", "Dumbbell", 3),
    ("Dumbbell External Rotation", "Shoulders", "Rotator Cuff", "isolation", "Dumbbell", 3),
    ("Cable External Rotation", "Shoulders", "Rotator Cuff", "isolation", "Cable", 3),

    # === Arms (42: 4 compound, 38 isolation) ===
    ("Close-Grip Bench Press", "Arms", "Triceps", "compound", "Barbell", 4),
    ("Tricep Dip", "Arms", "Triceps", "compound", "Bodyweight", 4),
    ("Weighted Chin-Up (Arms)", "Arms", "Biceps", "compound", "Bodyweight", 4),
    ("JM Press", "Arms", "Triceps", "compound", "Barbell", 3),
    ("Barbell Curl", "Arms", "Biceps", "isolation", "Barbell", 4),
    ("Dumbbell Curl", "Arms", "Biceps", "isolation", "Dumbbell", 3),
    ("Hammer Curl", "Arms", "Brachialis", "isolation", "Dumbbell", 3),
    ("Preacher Curl", "Arms", "Biceps", "isolation", "Machine", 3),
    ("Tricep Pushdown", "Arms", "Triceps", "isolation", "Cable", 3),
    ("Overhead Tricep Extension", "Arms", "Triceps", "isolation", "Dumbbell", 3),
    ("Skull Crusher", "Arms", "Triceps", "isolation", "Barbell", 3),
    ("EZ Bar Curl", "Arms", "Biceps", "isolation", "EZ Bar", 3),
    ("Concentration Curl", "Arms", "Biceps", "isolation", "Dumbbell", 3),
    ("Cable Curl", "Arms", "Biceps", "isolation", "Cable", 3),
    ("Incline Dumbbell Curl", "Arms", "Biceps", "isolation", "Dumbbell", 3),
    ("Spider Curl", "Arms", "Biceps", "isolation", "Dumbbell", 3),
    ("Cable Hammer Curl", "Arms", "Brachialis", "isolation", "Cable", 3),
    ("Reverse Curl", "Arms", "Forearms", "isolation", "Barbell", 3),
    ("Wrist Curl", "Arms", "Forearms", "isolation", "Barbell", 3),
    ("Reverse Wrist Curl", "Arms", "Forearms", "isolation", "Barbell", 3),
    ("Rope Pushdown", "Arms", "Triceps", "isolation", "Cable", 3),
    ("Single-Arm Tricep Pushdown", "Arms", "Triceps", "isolation", "Cable", 3),
    ("Overhead Cable Extension", "Arms", "Triceps", "isolation", "Cable", 3),
    ("Dumbbell Kickback", "Arms", "Triceps", "isolation", "Dumbbell", 3),
    ("EZ Bar Skull Crusher", "Arms", "Triceps", "isolation", "EZ Bar", 3),
    ("Single-Arm Overhead Extension", "Arms", "Triceps", "isolation", "Dumbbell", 3),
    ("Machine Tricep Extension", "Arms", "Triceps", "isolation", "Machine", 3),
    ("Machine Bicep Curl", "Arms", "Biceps", "isolation", "Machine", 3),
    ("Bayesian Curl", "Arms", "Biceps", "isolation", "Cable", 3),
    ("Cross-Body Hammer Curl", "Arms", "Brachialis", "isolation", "Dumbbell", 3),
    ("Zottman Curl", "Arms", "Biceps", "isolation", "Dumbbell", 3),
    ("Dumbbell Preacher Curl", "Arms", "Biceps", "isolation", "Dumbbell", 3),
    ("Cable Preacher Curl", "Arms", "Biceps", "isolation", "Cable", 3),
    ("EZ Bar Preacher Curl", "Arms", "Biceps", "isolation", "EZ Bar", 3),
    ("Behind-the-Back Wrist Curl", "Arms", "Forearms", "isolation", "Barbell", 3),
    ("Farmer's Walk", "Arms", "Forearms", "isolation", "Dumbbell", 3),
    ("Plate Pinch Hold", "Arms", "Forearms", "isolation", "Plate", 3),
    ("Tate Press", "Arms", "Triceps", "isolation", "Dumbbell", 3),
    ("French Press", "Arms", "Triceps", "isolation", "EZ Bar", 3),
    ("Close-Grip Push-Up", "Arms", "Triceps", "isolation", "Bodyweight", 3),
    ("Drag Curl", "Arms", "Biceps", "isolation", "Barbell", 3),
    ("21s Curl", "Arms", "Biceps", "isolation", "Barbell", 3),

    # === Core (40: 0 compound, 40 isolation) ===
    ("Plank", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 4),
    ("Hanging Leg Raise", "Core", "Lower Abs", "isolation", "Bodyweight", 4),
    ("Cable Crunch", "Core", "Rectus Abdominis", "isolation", "Cable", 3),
    ("Russian Twist", "Core", "Obliques", "isolation", "Bodyweight", 3),
    ("Ab Wheel Rollout", "Core", "Rectus Abdominis", "isolation", "Ab Wheel", 3),
    ("Side Plank", "Core", "Obliques", "isolation", "Bodyweight", 3),
    ("Woodchop", "Core", "Obliques", "isolation", "Cable", 3),
    ("Dead Bug", "Core", "Core Stability", "isolation", "Bodyweight", 3),
    ("Bicycle Crunch", "Core", "Obliques", "isolation", "Bodyweight", 3),
    ("Mountain Climber", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("V-Up", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("Toe Touch", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("Leg Raise (Floor)", "Core", "Lower Abs", "isolation", "Bodyweight", 3),
    ("Flutter Kicks", "Core", "Lower Abs", "isolation", "Bodyweight", 3),
    ("Scissor Kicks", "Core", "Lower Abs", "isolation", "Bodyweight", 3),
    ("Hollow Body Hold", "Core", "Core Stability", "isolation", "Bodyweight", 3),
    ("Dragon Flag", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("Pallof Press", "Core", "Core Stability", "isolation", "Cable", 3),
    ("Anti-Rotation Press", "Core", "Core Stability", "isolation", "Resistance Band", 3),
    ("Decline Sit-Up", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("Weighted Sit-Up", "Core", "Rectus Abdominis", "isolation", "Plate", 3),
    ("Hanging Knee Raise", "Core", "Lower Abs", "isolation", "Bodyweight", 3),
    ("Cable Woodchop (High to Low)", "Core", "Obliques", "isolation", "Cable", 3),
    ("Cable Woodchop (Low to High)", "Core", "Obliques", "isolation", "Cable", 3),
    ("Suitcase Carry", "Core", "Obliques", "isolation", "Dumbbell", 3),
    ("Copenhagen Plank", "Core", "Obliques", "isolation", "Bodyweight", 3),
    ("Bear Crawl", "Core", "Core Stability", "isolation", "Bodyweight", 3),
    ("Bird Dog", "Core", "Core Stability", "isolation", "Bodyweight", 3),
    ("Farmer's Carry", "Core", "Core Stability", "isolation", "Dumbbell", 3),
    ("L-Sit Hold", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("Toes to Bar", "Core", "Rectus Abdominis", "isolation", "Bodyweight", 3),
    ("GHD Sit-Up", "Core", "Rectus Abdominis", "isolation", "Machine", 3),
    ("Medicine Ball Slam", "Core", "Rectus Abdominis", "isolation", "Medicine Ball", 3),
    ("Medicine Ball Russian Twist", "Core", "Obliques", "isolation", "Medicine Ball", 3),
    ("Stability Ball Crunch", "Core", "Rectus Abdominis", "isolation", "Stability Ball", 3),
    ("Stability Ball Pike", "Core", "Rectus Abdominis", "isolation", "Stability Ball", 3),
    ("Cable Pallof Hold", "Core", "Core Stability", "isolation", "Cable", 3),
    ("Reverse Crunch", "Core", "Lower Abs", "isolation", "Bodyweight", 3),
    ("Windshield Wiper", "Core", "Obliques", "isolation", "Bodyweight", 3),
    ("Plank Shoulder Tap", "Core", "Core Stability", "isolation", "Bodyweight", 3),
]


async def seed(db: aiosqlite.Connection):
    await db.executemany(
        """INSERT OR IGNORE INTO exercises
           (name, muscle_group, sub_muscle_group, exercise_type, equipment, default_rating)
           VALUES (?, ?, ?, ?, ?, ?)""",
        EXERCISES,
    )
    await db.commit()
